### ISSUE TITLE
doubt about datasets setting

### ISSUE THREAD

**Issue by ShawnHuang497** [huyquoctrinh/MetaPolyp-CBMS2023#2]
Hi!
U said that "with training set from 50% of Kvasir-SEG and 50% of ClinicDB dataset" in the README.md, but U said "The
training, validating, and testing make up 60%, 20%, and 20%, respectively". 

So I'm confused about your datasets division setup, can you answer that?

**Comment by huyquoctrinh** [comment]
Thank you so much for this issue, data was gotten from the PraNet, and the training set is half of Kvasir-SEG and ClinicDB, then for the training stage, I split it 60:20:20 for train:val:test, and then I will use the test dataset from PraNet for benchmark the model. I hope this answer satisfy your question.

**Comment by ShawnHuang497** [comment]
Ok, thanks for your answer. And I am planing to follow your work, but the dataset link of Pranet is invalid. Can you send the splited datasets .zip or name list to me? My email is 2515950785@qq.com. 
Thanks.

**Comment by huyquoctrinh** [comment]
Hi, I have updated the link to download dataset on the README, I hope you can find that

**Comment by ShawnHuang497** [comment]
Great job! Thanks very much! Moreover, I do not see the test results of ClinicDB in your paper. Will you be releasing the results of ClinicDB test dataset?

**Comment by huyquoctrinh** [comment]
Hi, because at that time I don't have enough pages for writing, I have to choose 3 datasets for benchmark results...
