### ISSUE TITLE
issue during training

### ISSUE THREAD

**Issue by umang4002** [huyquoctrinh/MetaPolyp-CBMS2023#6]
![image](https://github.com/huyquoctrinh/MetaPolyp-CBMS2023/assets/111570202/6131e26f-6c23-449a-908a-155c95e8d17c)

**Comment by huyquoctrinh** [comment]
> ![image](https://github.com/huyquoctrinh/MetaPolyp-CBMS2023/assets/111570202/6131e26f-6c23-449a-908a-155c95e8d17c)
> 
> 

Hi, this issue looks like you miss / in your directory, it should be TrainDataset/masks/<image name>. I hope you can fix it

**Comment by umang4002** [comment]
Hi. Thankyou for the help. I have another doubt.
Can you please tell that what are the GPU and ram specifications for running train.py?

**Comment by umang4002** [comment]
And can it be run by decreasing the size on Nvidia T4 15 GB gpu ?

**Comment by huyquoctrinh** [comment]
> And can it be run by decreasing the size on Nvidia T4 15 GB gpu ?

Hi @umang4002 , it can run on T4, but you should decrease the batch size, also maybe colab limits your resource, so in some case you should do tuning to prevent OOM. I hope it's ok, let me know what can I help

**Comment by umang4002** [comment]
Hi.
Thankyou for reaching out.

**Comment by umang4002** [comment]
Thankyou  [huyquoctrinh](https://github.com/huyquoctrinh) the code was running fine on collab.

**Comment by huyquoctrinh** [comment]
Hi, it's my pleased to see it can run 😄
